# Generated by Django 4.2.3 on 2023-07-28 08:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0004_alter_products_images"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reviews",
            old_name="name",
            new_name="text",
        ),
    ]
